vich_uploader:
  db_driver: orm

  mappings:
    choice_image:
      uri_prefix: /images/choices
      upload_destination: "%kernel.project_dir%/public/images/choices"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      directory_namer:
        service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
        options:
          date_time_format: "Y/m/d" # will create directory "2018/23/09" for current date "2018-09-23"
          date_time_property: dateDeCreation
