vich_uploader:
  db_driver: orm

  mappings:
    choice_image:
      uri_prefix: /images/choices
      upload_destination: "%kernel.project_dir%/public/images/choices"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    plat_image:
      uri_prefix: /images/plats
      upload_destination: "%kernel.project_dir%/public/images/plats"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
